[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_GOOGLE_API_KEY = "AIzaSyCoPvaIsDYbp9dbhB_vSSMQZS9D16902BY"
  VITE_GOOGLE_CLIENT_ID = "302172555541-o4tdjvp06q3mci523e8rssr7j1de6mgg.apps.googleusercontent.com"
  VITE_GOOGLE_CALENDAR_ID = "primary"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"